"""empty message

Revision ID: 043fffed8d9f
Revises: 
Create Date: 2018-03-05 14:19:24.510903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043fffed8d9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('data_created', sa.DateTime(), nullable=True),
    sa.Column('data_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bucketlists')
    # ### end Alembic commands ###
